### ISSUE TITLE
Need a little more content

### ISSUE THREAD

**Issue by scottstanfield** [vertigo/vertigo.github.io#1]
Maybe a little animated gif of a yellow construction "coming soon"?

**Comment by toddpi314** [comment]
FYI, if your looking into hosting a site on github with static or Jekyll, notice that their CDN is not designed for speed. You will encounter 8-12s load times for static content from some locations.

**Comment by scottstanfield** [comment]
Not sure. Mike created this.

---

Scott Stanfield
scott@vertigo.commailto:scott@vertigo.com

On Jun 2, 2015, at 12:44 PM, Todd Morrison <notifications@github.com<mailto:notifications@github.com>> wrote:

What is this?

##

**Comment by toddpi314** [comment]
Cool. It is really designed for open source (non performance critical) sites.

**Comment by scottstanfield** [comment]
Yeah, I like the fact that it’s static. Will render fast.

**Comment by mhanley** [comment]
Sorry everyone, I was just reserving the domain name. Nothing to see here.

**Comment by scottstanfield** [comment]
Oh man!

I think we keep submitting requests and see how this goes :)

---

Scott Stanfield
scott@vertigo.commailto:scott@vertigo.com

On Jun 2, 2015, at 4:09 PM, Mike Hanley (Vertigo) <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry everyone, I was just reserving the domain name. Nothing to see here.

##

**Comment by staxmanade** [comment]
Be careful - you might a pull request to launch the site.

Be weary of they use http://togglejs.github.io/

**Comment by toddpi314** [comment]
4 posts from Scott. 3 posts from Todd. 1 post from Jason Jarret.
4 - 1 = 3
HALF LIFE 3 CONFIRMED

**Comment by scottstanfield** [comment]
Literally LOL'd on that.

---

Scott Stanfield
scott@vertigo.commailto:scott@vertigo.com

On Jun 3, 2015, at 6:31 AM, Todd Morrison <notifications@github.com<mailto:notifications@github.com>> wrote:

4 posts from Scott. 3 posts from Todd. 1 post from Jason Jarret.
4 - 1 = 3
HALF LIFE 3 CONFIRMED

##

**Comment by icecreammatt** [comment]
![community_image_1420456024](https://cloud.githubusercontent.com/assets/1154569/7975015/02242442-0a1e-11e5-9c30-a1cd0597102d.jpg)

**Comment by VertigoChris** [comment]
![munchies-i-have](https://cloud.githubusercontent.com/assets/8702216/7987174/a6147d00-0a90-11e5-8ef9-a26cf8271354.jpg)
